
ALL: BUILD_WIN RUN_WIN CLEAN_WIN

BUILD_WIN: 
	@cl ./(file).cpp /I ./$(directory/headers /o ./$(directory/bin/bindumpp.exe

BUILD_LINUX: 
	@g++ ./(file).cpp -I ./$(directory/headers -o ./$(directory/bin/bindumpp

RUN_WIN:
	./bin/bindump.exe $(file) $(parameters)

RUN_LINUX:
	./bin/bindump $(file) $(parameters)

CLEAN_WIN: 
	@del bindumpp.exe bindumpp.obj

CLEAN_LINUX: 
	@rm bindumpp 

INSTALL_WIN:


INSTALL_LINUX:


UNINSTALL_WIN:


UNINSTALL_LINUX:

