	
ALL: BUILD_WIN RUN_WIN CLEAN_WIN

BUILD_WIN: 
	@cl ./(file).c /I ./$(directory/headers /o ./$(directory/bin/cdump.exe

BUILD_LINUX: 
	@gCC ./(file).c -I ./$(directory/headers -o ./$(directory/bin/cdump

RUN_WIN:
	./bin/cdump.exe $(file) $(parameters)

RUN_LINUX:
	./bin/cdump $(file) $(parameters)

CLEAN_WIN: 
	@del cdump.exe cdump.obj

CLEAN_LINUX: 
	@rm cdump

INSTALL_WIN:


INSTALL_LINUX:


UNINSTALL_WIN:


UNINSTALL_LINUX:

